### ISSUE TITLE
导入Android studio 编译无法通过

### ISSUE THREAD

**Issue by ZhangLanqiu** [gdutxiaoxu/FunAPP#1]
Error:Configuration with name 'default' not found.

这个错报的我有点无语！ google了但是不懂，怎么调！

**Comment by LittleWaver** [comment]
删除工程目录setting.gradle文件中的", ':library'"和"include ':networkimageloader'"
删除Fun模块build.gradle文件中的"compile project(path: ':library')"
继而，可以编译通过
但是当你运行时，依旧错误连连：有类名与java文件名不一致（OnRefreshListener.java等），有类文件找不到（TouchImageView.java）。

**Comment by xlc1540697096** [comment]
我的也是楼上的错误，作者能不能先自己测试一下再发布啊！照顾一下新人。还有总是提示缺少module，作者应该使用正确的删除module方法，而不是简单地使用delete。

**Comment by gdutxiaoxu** [comment]
你pull一下，是我忘记提交library了，应该可以了 ，如果OK的 话，顺便close issue

**Comment by gdutxiaoxu** [comment]
@ZhangLanqiu @LittleWaver @xlc1540697096 解决了吗？

**Comment by LittleWaver** [comment]
编译通不过现在已经解决了
PS：两个类名和文件名不一致（FunAPP\Fun\src\main\java\com\xujun\funapp\model\PictureDetailModel.java; FunAPP\Fun\src\main\java\com\xujun\funapp\common\OnRefreshListener.java）

**Comment by xlc1540697096** [comment]
楼主，还是在报错，各种不存在
和楼上一样的错误，而且还有其他的错误

**Comment by firstxia** [comment]
没法看,错误很多,建议作者再看下

**Comment by LittleWaver** [comment]
现在已经是基本可以了的
pull一下或者重新导入AS
再修改文件名FunAPP\Fun\src\main\java\com\xujun\funapp\model\PictureDetailModel.java; FunAPP\Fun\src\main\java\com\xujun\funapp\common\OnRefreshListener.java
就可以编译通过并生成apk

**Comment by zhangy163** [comment]
我遇到这两个文件，将类改成小写的好像就行了

**Comment by xlc1540697096** [comment]
我的也弄好了，改名即可。

**Comment by zhangy163** [comment]
嘿嘿

**Comment by zhangy163** [comment]
我感觉我看不懂代码，咋办呢？好纠结

**Comment by gdutxiaoxu** [comment]
好，那就Ok了，那我就close掉这个issue
