### ISSUE TITLE
关于代码的注释以及文档

### ISSUE THREAD

**Issue by zhangy163** [gdutxiaoxu/FunAPP#2]
我的底子很差，在读你的代码的时候，觉着很困难。你能为此写一份参考文档吗？有些地方我压根看不懂。拜托啦

**Comment by gdutxiaoxu** [comment]
现在还没有开发完成，文档暂时还没有动手写。估计的年后才会 开始写，最近也没有在开发这个了，至于里面的一些知识点，对初学者可能有点比较难读懂，没事，我也正在学习中
